# fly.toml app configuration file generated for taskmaster-backend-hfj9hg on 2024-12-01T05:52:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'taskmaster-backend-hfj9hg'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024


[experimental]
  cmd = ["serve"]
  auto_rollback = true
  regions = ["jnb", "lhr", "syd"]  # Add additional regions here

